#!/bin/bash

echo "🔗 GitHub Integration Setup"
echo "=========================="
echo ""
echo "📋 Follow these steps to enable automatic deployments:"
echo ""
echo "1️⃣  Create GitHub Repository:"
echo "   • Go to: https://github.com/new"
echo "   • Repository name: ai-sales-suite"
echo "   • Description: AI Sales Suite - Autonomous sales engine"
echo "   • Make it PUBLIC"
echo "   • Don't initialize with README (we already have files)"
echo "   • Click 'Create repository'"
echo ""
echo "2️⃣  Copy the repository URL (it will look like):"
echo "   https://github.com/YOUR_USERNAME/ai-sales-suite.git"
echo ""
echo "3️⃣  Run these commands (replace YOUR_USERNAME):"
echo "   git remote add origin https://github.com/YOUR_USERNAME/ai-sales-suite.git"
echo "   git push -u origin main"
echo "   npx vercel git connect https://github.com/YOUR_USERNAME/ai-sales-suite.git"
echo ""
echo "🎯 After setup, every 'git push' will automatically deploy to Vercel!"
echo ""
echo "📱 Your live site will be at: https://ai-sales-suite.vercel.app"
